version: '3.4'

services:
    db:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
          MYSQL_ROOT_PASSWORD: example
        ports:
            - 3306:3306
            - 33060:33060
    adminer:
        image: adminer
        restart: always
        ports:
            - 8080:8080
    rabbitmq:
        image: rabbitmq:management-alpine
        ports:
            - 15671:15671
            - 15672:15672
            - 15691:15691
            - 15692:15692
            - 25672:25672
            - 4369:4369
            - 5671:5671
            - 5672:5672